FROM crystallang/crystal:0.36.1-alpine

RUN apk --update add postgresql-client

ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

ADD shard* $INSTALL_PATH/

RUN shards install

COPY . $INSTALL_PATH